### ISSUE TITLE
Markdown guide for examples

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestorm.js#253]
I'd like to see this feature in docs/examples. Some "complex" or popular examples should have alike description tab that explains:
 - How to build such app step-by-step
 - Which modules were used (that are not in whs build)
 - Some tips that you should note while making a similar thing

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [ ] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by noahcoetsee** [comment]
Assign it to me sasha

**Comment by sasha240100** [comment]
@TheCodeCrafter done.

**TODO**:

- [x] Make a simple template for an article
- [x] Add `article.md` to example folders
- [x] Write step-by-step explanation for `basic / helloworld` example

**Comment by noahcoetsee** [comment]
Basis done. NOW: WORKING ON DOING BASIC, THEN VR, THEN LIGHTS, THEN PHYSICS, and so on

**Comment by sasha240100** [comment]
@TheCodeCrafter OK, reviewing

**Comment by hirako2000** [comment]
Let's try to merge the big work @TheCodeCrafter done so far, and spawn a separate issue for VR etc? (whatever is  left).
Would be good to release 2.1.9, we have many fixes merged so far.
